services:
  chirpstack-integration-pulsar:
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./:/chirpstack-integration-pulsar
    depends_on:
      - pulsar

  pulsar:
    image: 'apachepulsar/pulsar:2.11.1'
    command: 'bin/pulsar standalone'
    ports:
      - "6650:6650"
