#!/usr/bin/env bash

# Set config-file permissions
chown -R chirpstack:chirpstack /etc/chirpstack-pulsar-integration
chmod 750 /etc/chirpstack-pulsar-integration
chmod 640 /etc/chirpstack-pulsar-integration/*.toml

#DEBHELPER#
